name: hankan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  get_it: ^8.0.3
  dio: ^5.8.0
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  shadcn_ui: ^0.15.0
  persistent_bottom_nav_bar_v2: ^5.4.0
  material_symbols_icons: ^4.2873.0
  animated_text_kit: ^4.2.3
  sendbird_chat_widget: ^1.0.4
  sendbird_chat_sdk: ^4.5.2
  kpostal_web: ^0.0.6
  url_launcher: ^6.3.1
  kpostal: ^1.1.0
  image_picker: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
